"""One-off migration: creates the `qa_cache` table on an EXISTING
PostgreSQL database.

`apply_schema.py` runs the whole of schema.sql, which is already
idempotent, so that would work too. This exists for the same reason
`migrate_leads_columns.py` does: on a live database you want a single,
obviously-scoped script that touches one table and prints what it did,
rather than re-running the whole schema and hoping every statement really
was a no-op.

Safe to re-run — CREATE TABLE IF NOT EXISTS does nothing when the table
already exists.

Run: python migrate_qa_cache.py
"""

from __future__ import annotations

from dotenv import load_dotenv

load_dotenv()

from app.db import get_connection  # noqa: E402

_CREATE_QA_CACHE = """
CREATE EXTENSION IF NOT EXISTS vector;

CREATE TABLE IF NOT EXISTS qa_cache (
    id                  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    question_hash       CHAR(64)      NOT NULL,
    question_text       VARCHAR(300)  NOT NULL,
    question_embedding  vector(768)   NOT NULL,
    embedding_dim       SMALLINT      NOT NULL,
    answer              TEXT          NOT NULL,
    grounded            BOOLEAN       NOT NULL DEFAULT TRUE,
    kb_signature        VARCHAR(255)  NOT NULL,
    embedding_model     VARCHAR(100)  NOT NULL,
    llm_model           VARCHAR(100)  NOT NULL,
    hit_count           INTEGER       NOT NULL DEFAULT 0,
    created_at          TIMESTAMPTZ   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_hit_at         TIMESTAMPTZ   NULL,
    CONSTRAINT uq_qa_cache_question UNIQUE (question_hash)
);

CREATE INDEX IF NOT EXISTS ix_qa_cache_scope
    ON qa_cache (kb_signature, embedding_model, llm_model);
"""

_EXPECTED_COLUMNS = (
    "question_hash", "question_embedding", "answer", "kb_signature",
    "embedding_model", "llm_model", "hit_count",
)


def main() -> None:
    conn = get_connection()
    try:
        with conn.cursor() as cursor:
            cursor.execute(_CREATE_QA_CACHE)
        conn.commit()
        print("Applied: CREATE TABLE IF NOT EXISTS qa_cache")
    finally:
        conn.close()

    # Verify rather than trusting the CREATE reported success.
    conn = get_connection()
    try:
        with conn.cursor() as cursor:
            cursor.execute(
                "SELECT column_name FROM information_schema.columns "
                "WHERE table_name = 'qa_cache'"
            )
            columns = [row[0] for row in cursor.fetchall()]
    finally:
        conn.close()

    print("\nqa_cache columns now:", columns)
    missing = [c for c in _EXPECTED_COLUMNS if c not in columns]
    if missing:
        print(f"\nSTILL MISSING: {missing} — something went wrong above.")
    else:
        print("\nAll expected columns confirmed present.")


if __name__ == "__main__":
    main()
