-- Apex Creative AI Chat — PostgreSQL schema (pgvector)
--
-- Ported from MySQL. This is a genuine port, not a syntax translation:
-- five MySQL behaviours have no Postgres equivalent and are handled
-- explicitly below, each noted where it appears.
--
--   1. AUTO_INCREMENT            -> GENERATED BY DEFAULT AS IDENTITY
--   2. ON UPDATE CURRENT_TIMESTAMP -> a trigger; Postgres has no column
--                                   -level equivalent, and the debounced
--                                   lead email depends on it
--   3. ENUM('a','b')             -> CHECK constraint, so adding a value
--                                   later is a one-line change instead
--                                   of an ALTER TYPE migration
--   4. LONGBLOB + embedding_dim  -> vector(768), a real type
--   5. CRC32() in the freshness  -> md5(); Postgres has no crc32
--      fingerprint
--
-- WHY vector(768) AND NOT A LARGER COLUMN
-- The dimension is fixed at creation, so it encodes a decision already
-- made: gemini-embedding-001 was measured against two local multilingual
-- models and won (see eval/embedding_comparison.md). Changing embedding
-- model later means ALTERing this column AND a full re-ingest — the two
-- are one migration, not two independent changes.
--
-- WHAT IS DELIBERATELY ABSENT: an HNSW or IVFFlat index on the embedding.
-- Those are approximate indexes built for 10k+ vectors. At 52 sections an
-- index is slower than a sequential scan and less accurate, since exact
-- search is currently free. Add one when the KB passes a few thousand
-- sections, not before.

CREATE EXTENSION IF NOT EXISTS vector;

-- Sets updated_at/last_active_at on UPDATE, replacing MySQL's
-- ON UPDATE CURRENT_TIMESTAMP. Written generically so both tables share
-- one function rather than duplicating a trigger body.
CREATE OR REPLACE FUNCTION touch_updated_column() RETURNS trigger AS $$
BEGIN
    NEW.updated_at = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TABLE IF NOT EXISTS kb_chunks (
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    section_title   VARCHAR(255)  NOT NULL,
    content         TEXT          NOT NULL,
    content_hash    CHAR(64)      NOT NULL,
    -- Was LONGBLOB holding struct-packed float32s, with embedding_dim
    -- carried alongside so a mismatch could be detected. The type now
    -- enforces what that pair only documented.
    embedding       vector(768)   NOT NULL,
    embedding_dim   SMALLINT      NOT NULL,
    embedding_model VARCHAR(100)  NOT NULL,
    last_updated    TIMESTAMPTZ   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_kb_chunks_section_title UNIQUE (section_title)
);

-- The same chunks embedded a SECOND time, by the local fallback model.
--
-- The Gemini free tier allows 1,000 embed requests per day and every chat
-- turn spends one, so when it runs out the bot cannot embed a question and
-- answers nothing at all until midnight Pacific. The fallback provider
-- keeps it running on a local model meanwhile.
--
-- That requires a second set of vectors, because the two models occupy
-- different spaces: scoring a bge-m3 query against Gemini chunks does not
-- fail, it returns confidently-ranked nonsense. Retrieval therefore picks
-- the vector set by MODEL NAME, never by dimension -- two models can share
-- a dimension, and one already did here.
--
-- A separate table rather than more columns on kb_chunks: the ingest path
-- stays untouched, ON DELETE CASCADE keeps the two in step when a section
-- is removed, and an absent row simply means "no fallback for this chunk"
-- rather than a half-populated column. content_hash is copied from
-- kb_chunks so staleness is detectable after a re-ingest.
--
-- Populate with scripts/build_fallback_index.py (costs no Gemini quota).
CREATE TABLE IF NOT EXISTS kb_chunk_fallback_vectors (
    chunk_id        INTEGER      PRIMARY KEY
                    REFERENCES kb_chunks(id) ON DELETE CASCADE,
    embedding       vector(768)  NOT NULL,
    embedding_dim   SMALLINT     NOT NULL,
    embedding_model VARCHAR(100) NOT NULL,
    content_hash    CHAR(64)     NOT NULL,
    updated_at      TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS ix_kb_fallback_model
    ON kb_chunk_fallback_vectors (embedding_model);

CREATE TABLE IF NOT EXISTS leads (
    id                  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name                VARCHAR(255),
    email               VARCHAR(255),
    phone               VARCHAR(50),
    whatsapp_number     VARCHAR(50),
    company             VARCHAR(255),
    business_type       VARCHAR(255),
    service_requested   VARCHAR(255),
    budget              VARCHAR(100),
    timeline            VARCHAR(100),
    notes               TEXT,
    chat_summary        TEXT,
    -- MySQL ENUM. A CHECK keeps the same guarantee while letting a new
    -- status be added without ALTER TYPE and its lock.
    status              VARCHAR(20) NOT NULL DEFAULT 'new'
                        CHECK (status IN ('new', 'escalated', 'contacted', 'closed')),
    notified_at         TIMESTAMPTZ NULL,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS sessions (
    session_id      CHAR(36)    PRIMARY KEY,   -- client-generated UUID
    created_at      TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    -- The debounced lead email fires on "no new message for N minutes",
    -- so this column is load-bearing, not decorative. In MySQL it was
    -- maintained by ON UPDATE CURRENT_TIMESTAMP; here a trigger does it.
    last_active_at  TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    lead_id         INTEGER     NULL REFERENCES leads(id)
);

CREATE TABLE IF NOT EXISTS messages (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id      CHAR(36)    NOT NULL REFERENCES sessions(session_id),
    role            VARCHAR(16) NOT NULL CHECK (role IN ('user', 'assistant')),
    content         TEXT        NOT NULL,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS ix_messages_session_created
    ON messages (session_id, created_at);

-- Cache-augmented generation. See app/rag/qa_cache.py for the rules on
-- what may be stored; kb_signature/embedding_model/llm_model are part of
-- every lookup, not metadata, so re-ingesting retires prior answers.
CREATE TABLE IF NOT EXISTS qa_cache (
    id                  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    question_hash       CHAR(64)      NOT NULL,
    question_text       VARCHAR(300)  NOT NULL,
    question_embedding  vector(768)   NOT NULL,
    embedding_dim       SMALLINT      NOT NULL,
    answer              TEXT          NOT NULL,
    grounded            BOOLEAN       NOT NULL DEFAULT TRUE,
    kb_signature        VARCHAR(255)  NOT NULL,
    embedding_model     VARCHAR(100)  NOT NULL,
    llm_model           VARCHAR(100)  NOT NULL,
    hit_count           INTEGER       NOT NULL DEFAULT 0,
    created_at          TIMESTAMPTZ   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_hit_at         TIMESTAMPTZ   NULL,
    CONSTRAINT uq_qa_cache_question UNIQUE (question_hash)
);
CREATE INDEX IF NOT EXISTS ix_qa_cache_scope
    ON qa_cache (kb_signature, embedding_model, llm_model);

DROP TRIGGER IF EXISTS trg_leads_updated_at ON leads;
CREATE TRIGGER trg_leads_updated_at BEFORE UPDATE ON leads
    FOR EACH ROW EXECUTE FUNCTION touch_updated_column();